typeset -U path

HISTFILE="$XDG_STATE_HOME/zsh/history"
HISTSIZE=1000
SAVEHIST=1000
setopt share_history
setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY

autoload -Uz compinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"
zstyle ":completion:" menu select

alias ..='cd ..'
alias ...='cd ../..'

alias vim=nvim
alias k=kubecolor

alias ll='eza -l --icons --group-directories-first -hH'
alias la='eza -la --icons --group-directories-first -hH'

alias gs='git status'

alias chrome="google-chrome \
  --enable-features=UseOzonePlatform \
  --ozone-platform=wayland \
  >/dev/null 2>&1 & disown"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# zsh-autosuggestions: load *after* Starship/zoxide so widget wrapping order is stable.
# MANUAL_REBIND stops rebinding every precmd (large win with other ZLE wrappers; see plugin README).
export ZSH_AUTOSUGGEST_MANUAL_REBIND=
export ZSH_AUTOSUGGEST_STRATEGY=(history)
source "$XDG_DATA_HOME/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

source "$XDG_DATA_HOME/zsh/plugins/gclone/gclone.zsh"

