unbind-key C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
unbind-key '"'
unbind-key %

bind-key c new-window -c "#{pane_current_path}"

bind-key r source-file ~/.tmux.conf

set-option -g mouse on
set-option -g escape-time 20

set-option -g status-position top

set-option -g default-terminal "tmux-256color"
set-option -as terminal-features ',xterm-256color:RGB'
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@:indn@,tmux*:indn@'

set-option -g focus-events on

set-option -g @plugin 'tmux-plugins/tpm'

set-option -g @plugin 'christoomey/vim-tmux-navigator'
set-option -g @plugin 'catppuccin/tmux#v2.3.0'

set-option -g @catppuccin_flavor 'latte'

set-option -g status-right-length 100
set-option -g status-left-length 100
set-option -g status-left ''

set-option -g status-right "#{E:@catppuccin_status_application}"
set-option -ag status-right "#{E:@catppuccin_status_session}"
set-option -ag status-right "#{E:@catppuccin_status_uptime}"


run '~/.tmux/plugins/tpm/tpm'
